---

- hosts: satellite
  connection: local
  tasks:

  - name: disable all repositories
    command: "subscription-manager repos --disable '*'"
    tags: rhsm

  - name: enable satellite 6 repositories
    command: "subscription-manager repos --enable rhel-7-server-rpms --enable rhel-server-rhscl-7-rpms --enable rhel-7-server-satellite-6.2-rpms"
    tags: rhsm

  - name: make sure firewalld is enabled and running
    service:
      name: firewalld
      state: started
      enabled: true
    tags: firewalld

  - name: open firewalld ports
    firewalld:
      immediate: yes
      permanent: yes
      state: enabled
      port: "{{ item }}"
    with_items: "{{ open_ports }}" 
    tags: firewalld

  - name: make sure selinux is in enforcing mode
    selinux:
      policy: targeted
      state: enforcing
    tags: selinux

# these tasks verify that DNS is configured properly
# if any of these tasks fail, the installation won't complete successully

  - name: verify localhost resolution
    command: "ping -c1 localhost"
    changed_when: false
    tags: dns

  - name: verify hostname resolution 
    command: "ping -c1 {{ ansible_hostname }}"
    changed_when: false
    tags: dns

  - name: verify FQDN resolution
    command: "ping -c1 {{ ansible_fqdn }}"
    changed_when: false
    tags: dns

  - name: perform yum update
    yum:
      name: "*"
      state: latest
      update_cache: yes
    tags: yum
 
  - name: install satellite packages
    yum:
      name: satellite
      state: latest 
    tags: yum

# this task will run the satellite-installer
# it will be run with basic configuration (no capsule services like DNS, DHCP etc) 
# more configuration can be added manually later, see "satellite-installer --help" for all options

  - name: run satellite-installer (this will take a while...)
    command: "satellite-installer --scenario satellite --foreman-initial-organization '{{ organization }}' --foreman-initial-location '{{ location }}' --foreman-admin-password '{{ admin_password }}'"
    tags: satellite-installer

# debug task to check installer command
#  - name: run satellite-installer (this will take a while...)
#    debug:
#      msg: "satellite-installer --scenario satellite --foreman-initial-organization '{{ organization }}' --foreman-initial-location '{{ location }}' --foreman-admin-password '{{ admin_password }}'"
#    tags: satellite-installer

  - name: notify user that installation is complete
    debug: 
      msg: "The installation is now complete. A reboot might be in place if yum updated packages that required reboot. After that it is time to configure your Satellite. This can be done with sat6-configure.yaml"
    tags: satellite-installer
