- name: attach subscriptions to activation keys
  shell: >
    hammer activation-key add-subscription
    --name 'AK-{{ lifecycle_environment.name }}-{{ item.0.name }}'
    --subscription-id $(hammer --csv subscription list --search '{{ item[1] }}' | tail -n +2 | awk -F ',' '{print $1}')
  with_subelements:
  - "{{ profiles }}"
  - subscriptions
  tags: activation_keys

