---

- name: get all filters for "{{ content_view.name }}"
  shell: hammer --csv content-view filter list --content-view '{{ content_view.name }}' | tail -n +2 | awk -F ',' '{print $1}' 
  register: filter_ids
  changed_when: false

- name: delete all filters for "{{ content_view.name }}" 
  command: >
    hammer content-view filter delete
    --content-view '{{ content_view.name }}'
    --id '{{ item }}'
  with_items: "{{ filter_ids.stdout_lines }}"
