---

- name: attach subscriptions to activation keys
  shell: >
    hammer activation-key add-subscription
    --organization '{{ organization }}'
    --name 'AK-{{ lifecycle_environment.name }}-{{ item.0.name }}'
    --subscription-id $(hammer --csv subscription list --organization '{{ organization }}' --search '{{ item.1.name }}' | tail -n +2 | awk -F ',' '{print $1}')
  register: attach_output
  changed_when: 'attach_output.rc == 0'
  failed_when: 'attach_output.rc != 0 and attach_output.rc != 128'
  with_nested:
  - "{{ content_views }}"
  - "{{ custom_products }}"
