---

- name: get current organizations
  shell: hammer --csv organization list | tail -n +2 | awk -F ',' '{print $2}'
  register: current_organizations
  changed_when: false

- name: ensure organizations exists
  command: hammer organization create --name "{{ organization }}"
  when: 'organization not in current_organizations.stdout'

