---

- name: override smart class parameters
  when: smart_class_parameters_override is defined
  command: >
    hammer sc-param update
    --puppet-class '{{ item.0.class_name }}'
    --name '{{ item.1 }}'
    --override true
  with_subelements:
  - "{{ smart_class_parameters_override }}"
  - parameter_names
